#!/usr/bin/env bash
# uses scp to upload a file into a server

if [ $# -lt 3 ]
then
       	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else 
	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~ -i "$4"
fi


