#!/usr/bin/env bash
# uses scp to upload a file into a server

if [ $# -lt 4 ]
then
       	echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
	scp -o StrictHostKeyChecking=no "$1" "$3"@"2":~/
else
	scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/ -i "$4"
fi


