#!/usr/bin/env bash
#Installs and configures nginx
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#create absolute path
AB_PATH=/var/www/html
mkdir -p "$AB_PATH"

#set permissions
sudo chmod -R 755 "$AB_PATH"
sudo chown -R "$USER":"$USER" "$AB_PATH"

#set content
echo 'Hello World!' > "$AB_PATH/index.nginx-debian.html"

#set up redirect
CONFIG_BLOCK=$(cat <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;

    server_name _;
    
    location /redirect_me {

	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}


    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL
)

# Add Nginx configuration to the default file using sed
sudo sed -i '/server {/r /dev/stdin' /etc/nginx/sites-available/default <<< "$CONFIG_BLOCK"
#start nginx
sudo service nginx start
