#!/usr/bin/env bash
#Installs and configures nginx
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

#set content
echo 'Hello World!' | sudo tee /var/www/html/index

#set up redirect
udo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
#start nginx
sudo service nginx restart
