#!/usr/bin/env bash
#create an sql dump of all databases

if [ $# -lt 1 ];
then
	echo "Usage: Mysql user password needed"
	exit 1
fi

mysqldump -u root -p "$1" database tyrell_crop > backup.sql
tar -czvf "$(date +%d-%m-%Y).tar.gz" backup.sql

