#!/usr/bin/env bash
#Recieves  and evaluates multiple signals

file="/var/run/myscript.pid"
if [ ! -e "$file" ]; then 
	touch "$file"
fi

sleep 2 && echo "$$" > "$file"


function sigterm_cleanup () {
	echo "I hate the kill command"
	rm "$file"
	exit 1
}

function sigquit_cleanup () {
	rm "$file"
	exit 1
}

trap sigterm_cleanup SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap sigquit_cleanup SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
