#!/usr/bin/env bash
#Edit the hosts file with new mappings
# the cp command is used due to a docker problem\
# the hosts file

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
